<?php
/* @var Magmodules\Shopreview\ViewModel\Review\Listing $viewModel */
$viewModel = $block->getViewModel();

/* @var \Magmodules\Shopreview\ViewModel\Form\View $formModel */
$formModel = $block->getFormModel();

/* @var \Magmodules\Shopreview\Api\Form\DataInterface $form */
$form = $formModel->getForm();

$reviewCount = count($viewModel->getReviews());
?>

<div class="shop-reviews mt-3">
    <div class="shop-reviews_header flex flex-wrap 
        <?= $reviewCount ? 'border-b border-stone-300 mb-11 pb-4 md:justify-between md:items-center': '' ?>">
        <?php if ($reviewCount): ?>
            <div class="shop-reviews_summary mb-8 w-full md:mb-0 md:w-auto">
                <?php
                    $rating = $viewModel->getReviewsRating();
                    $score = $rating['average'];
                    $reviews = $rating['reviews'];
                ?>

                <div class="rating-summary relative inline-block -ml-2">
                    <?php $starsWidth = ($score / 5) * 100; ?>

                    <div class="empty-starts flex text-stone-200">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-10 h-10">
                            <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path>
                        </svg>
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-10 h-10">
                            <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path>
                        </svg>
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-10 h-10">
                            <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path>
                        </svg>
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-10 h-10">
                            <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path>
                        </svg>
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-10 h-10">
                            <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path>
                        </svg>
                    </div>

                    <div class="filling-starts absolute top-0 text-yellow-400 overflow-hidden"
                         title="<?= $block->escapeHtml($starsWidth); ?>%"
                         style="width: <?= $block->escapeHtml($starsWidth); ?>%">

                        <div class="inline-flex">
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-10 h-10">
                                <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path>
                            </svg>
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-10 h-10">
                                <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path>
                            </svg>
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-10 h-10">
                                <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path>
                            </svg>
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-10 h-10">
                                <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path>
                            </svg>
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-10 h-10">
                                <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path>
                            </svg>
                        </div>
                    </div>
                </div>

                <p class="shop-reviews-widget_scores -mt-1 text-stone-700">
                    <?= /* @noEscape */ __('Scores: <b class="text-xl">%1</b>/<b class="text-sm font-normal">5</b>', number_format($score, 2, '.', '')) ?>
                    <?php $plural = ($reviews > 1) ? ('s') : (''); ?>

                    <span class="text-sm opacity-80">
                        ( <?= __('based on'); ?>
                        <a  class="underline underline-offset-4 transition-colors duration-300 text-blue-700 hover:text-blue-900"
                            href="<?= $block->escapeHtml($block->getReviewListingLink()) ?>">
                            <?= /* @noEscape */ __('%1 review%2', $reviews, $plural) ?>
                        </a> )
                    </span>
                </p>
            </div>
        <?php else: ?>
            <div class="mb-3 w-full">
                <?= __('This shop has no reviews yet.') ?>
            </div>
        <?php endif; ?>

        <?php if ($viewModel->isAllowReview($formModel->getFormOption($form, 'customer_group'))): ?>
            <a  class="btn btn-primary"
                href="<?= $block->escapeHtml($viewModel->getFormUrl()) ?>"
                title="<?= $block->escapeHtml(__('Submit a review')) ?>"
                aria-label="<?= $block->escapeHtml(__('Submit a review')) ?>">
                <?= $block->escapeHtml(__('Submit a review')) ?>
            </a>
        <?php endif; ?>
    </div>

    <?php /* @var \Magmodules\Shopreview\Api\Review\DataInterface $review */ ?>
    <div class="grid gap-6 mb-5">
        <?php foreach ($viewModel->getReviews() as $review): ?>
            <div class="shop-review border-b border-stone-300 pb-5">
                <div class="review-data grid gap-3 md:table">
                    <?php /* @var \Magmodules\Shopreview\Api\ReviewOptions\DataInterface $option */ ?>
                    <?php foreach ($review->getReviewOptions() as $option): ?>
                        <?php if (!$option->getVisibleInListing()) {
                            continue;
                        }?>

                        <?php if ($option->getType() == 'rating'): ?>
                            <?php $starsWidth = $option->getValue() / 5 * 100; ?>
                            <div class="review-rating flex gap-5 [&+.review-rating]:-mt-4 md:table-row">
                                <b class="label md:table-cell md:align-top md:pr-5"><?= $block->escapeHtml($option->getLabel()) ?>:</b>
                                <div class="block md:table-cell md:align-top">
                                    <div class="rating-summary relative inline-block -ml-1">
                                        <div class="empty-starts flex text-stone-200">
                                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-6 h-6">
                                                <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path>
                                            </svg>
                                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-6 h-6">
                                                <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path>
                                            </svg>
                                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-6 h-6">
                                                <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path>
                                            </svg>
                                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-6 h-6">
                                                <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path>
                                            </svg>
                                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-6 h-6">
                                                <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path>
                                            </svg>
                                        </div>

                                        <div class="filling-starts absolute top-0 text-yellow-400 overflow-hidden"
                                            title="<?= $block->escapeHtml($starsWidth); ?>%"
                                            style="width: <?= $block->escapeHtml($starsWidth); ?>%">

                                            <div class="inline-flex">
                                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-6 h-6">
                                                    <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path>
                                                </svg>
                                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-6 h-6">
                                                    <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path>
                                                </svg>
                                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-6 h-6">
                                                    <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path>
                                                </svg>
                                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-6 h-6">
                                                    <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path>
                                                </svg>
                                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-6 h-6">
                                                    <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path>
                                                </svg>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <?php else: ?>
                            <?php if($option->getValue()): ?>
                                <div class="review-text md:table-row <?= $block->escapeHtml($option->getType()) ?>">
                                    <b class="label md:table-cell md:align-top md:pr-5"><?= $block->escapeHtml($option->getLabel()) ?>:</b>
                                    <span class="value block md:table-cell md:align-top"><?= $block->escapeHtml($option->getValue()) ?></span>
                                </div>
                            <?php endif; ?>
                        <?php endif; ?>
                    <?php endforeach; ?>
                    <?php if ($comment = $viewModel->getComment((int)$review->getReviewId())):?>
                        <div class="comment"><?=$block->escapeHtml($comment)?></div>
                    <?php endif; ?>
                </div>

                <div class="review-date mt-4 text-sm text-right opacity-70">
                    <?= $block->escapeHtml(date_format(date_create($review->getCreatedAt()), "F j, Y")); ?>
                </div>
            </div>
        <?php endforeach; ?>
    </div>

    <div class="review-toolbar flex flex-wrap gap-6 items-center w-full sm:flex-nowrap">
        <?php if ($viewModel->showPaging()): ?>
            <div class="pages">
                <ul class="relative z-0 inline-flex shadow-sm items pages-items" aria-labelledby="paging-label">
                    <?php if ($viewModel->getPrevUrl()): ?>
                        <li class="item pages-item-previous">
                            <a class="action relative inline-flex items-center text-sm font-medium leading-5 
                                    bg-white border border-gray-300 transition duration-150 ease-in-out 
                                    hover:text-gray-400 focus:outline-none 
                                    focus:shadow-outline-blue active:bg-gray-100 active:text-gray-500 
                                    rounded-l-md px-3 py-2 text-gray-500"
                                href="<?= $block->escapeHtml($viewModel->getPrevUrl()) ?>"
                                title="Previous">
                                <span aria-label="Previous">
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" width="20" height="20">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"></path>
                                    </svg>
                                </span>
                            </a>
                        </li>
                    <?php endif; ?>

                    <?php foreach ($viewModel->getPaging() as $page): ?>
                        <li class="item -ml-px <?= $page['current'] ? 'current ' : '' ?>">
                            <?php if ($page['url']): ?>
                                <a  class="page relative inline-flex items-center text-sm font-medium leading-5 bg-white border 
                                        border-gray-300 transition duration-150 ease-in-out hover:text-gray-400 
                                        focus:outline-none focus:shadow-outline-blue
                                        active:bg-gray-100 active:text-gray-500 px-4 py-2 text-gray-700
                                        <?= $page['current'] ? 'bg-gray-100 !border-primary pointer-events-none z-10' : '' ?>"
                                    href="<?= $block->escapeHtml($page['url']) ?>">
                            <?php endif ?>
                                <span class="sr-only label">Page</span>
                                <span><?= $block->escapeHtml($page['label']) ?></span>
                        <?php if ($page['url']): ?>
                            </a>
                        <?php endif ?>
                        </li>
                    <?php endforeach ?>

                    <?php if ($viewModel->getNextUrl()): ?>
                        <li class="item pages-item-next -ml-px">
                            <a class="action next relative inline-flex items-center text-sm font-medium leading-5
                                    bg-white border border-gray-300 transition duration-150 ease-in-out 
                                    hover:text-gray-400 focus:outline-none 
                                    focus:shadow-outline-blue active:bg-gray-100 active:text-gray-500 rounded-r-md 
                                    px-3 py-2 text-gray-500"
                                href="<?= $block->escapeHtml($viewModel->getNextUrl()) ?>" 
                                title="Next">

                                <span aria-label="Next">
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" width="20" height="20">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path>
                                    </svg>
                                </span>
                            </a>
                        </li>
                    <?php endif; ?>
                </ul>
            </div>
        <?php endif ?>

        <?php if ($reviewCount): ?>
            <select class="form-select px-4 py-2 bg-white pr-10 sm:ml-auto" 
                    onchange="this.options[this.selectedIndex].value
                        && (window.location = this.options[this.selectedIndex].value);">
                
                <?php $sorting = $viewModel->getSorting(); ?>

                <option value="<?= $block->escapeUrl($block->getUrl(
                            'shopreview/review/listing',
                            $viewModel->getUrlParam($sorting['current']['sort_by'], $sorting['current']['direction'])
                        )) ?>">
                    <?= $block->escapeHtml($sorting['current']['label']); ?>
                </option>

                <?php foreach ($sorting['all'] as $item): ?>
                    <option value="<?= $block->escapeUrl($block->getUrl(
                                'shopreview/review/listing',
                                $viewModel->getUrlParam($item['sort_by'], $item['direction'])
                            )) ?> ">
                        <?= $block->escapeHtml($item['label']); ?>
                    </option>
                <?php endforeach ?>
            </select>
        <?php endif; ?>
    </div>
</div>
